### ISSUE TITLE
Release to Hackage?

### ISSUE THREAD

**Issue by srid** [well-typed/ixset-typed#17]
Would be great to get this for GHC 9 compatibility: https://github.com/well-typed/ixset-typed/pull/16

**Comment by stepcut** [comment]
I opened a pull request that adds support for template-haskell 2.18 as well. It would be lovely to see it on hackage as I have a dozen packages that directly or indirectly depend on it.

If you add me as a maintainer here and on hackage, I would be happy to help keep it building and uploaded.

**Comment by kosmikus** [comment]
@stepcut Thanks for the offer. I granted you maintainer permissions for this repo for the time being. I'm in principle happy to give you upload permissions for Hackage as well. Should you have bigger plans for this package though, and also in general, I'd be grateful if you first coordinate with me.
