### ISSUE TITLE
upper bound on template-haskell

### ISSUE THREAD

**Issue by clinty** [well-typed/ixset-typed#20]
ixset-typed appears to build fine with template-haskell 2.19

**Comment by Bodigrim** [comment]
As a Hackage trustee I made a revision: https://hackage.haskell.org/package/ixset-typed-0.5.1.0/revisions/

**Comment by andreasabel** [comment]
This issue came back for GHC 9.8
> rejecting: ixset-typed-0.5.1.0 (conflict: template-haskell==2.21.0.0/installed-be6e, ixset-typed => template-haskell>=2.8 && <2.21)

**Comment by clinty** [comment]
I believe a code change is needed for that.
